import {GraphFactory} from "../../src/model/GraphFactory";
import { Graph } from "../../src/model/Graph";

describe("MyGraphIterator", () => {
  // TODO: ryan having this const duplicated in code is bad!
  const minJSONGraph1Str = "{\r\n  \"nodes\": [\r\n    {\r\n      \"id\": \"h\",\r\n      \"metadata\": {\r\n        \"isHead\": true,\r\n    \t  \"title\" : \"\"\r\n      }\r\n    },\r\n    {\r\n      \"id\": \"q1\",\r\n      \"metadata\": {\r\n    \t  \"title\" : \"Do you play video games?\"\r\n      }\r\n    },\r\n    {\r\n      \"id\": \"q2\",\r\n      \"metadata\": {\r\n    \t  \"title\" : \"Do you play League of Legends or World of Warcraft Classic?\"\r\n      }\r\n    },\r\n    {\r\n      \"id\": \"q3\",\r\n      \"metadata\": {\r\n    \t  \"title\" : \"Do you exercise at least twice a week?\"\r\n      }\r\n    },\r\n    {\r\n      \"id\": \"q4\",\r\n      \"metadata\": {\r\n    \t  \"title\" : \"Do you get more than 7 hours of sleep every night?\"\r\n      }\r\n    },\r\n    {\r\n      \"id\": \"fn\",\r\n      \"metadata\": {\r\n        \"isFinalNode\" : true,\r\n    \t  \"title\" : \"\"\r\n      }\r\n    }\r\n  ],\r\n  \"edges\": [\r\n    {\r\n      \"source\": \"h\",\r\n      \"target\": \"q1\"\r\n    },\r\n    {\r\n      \"source\": \"q1\",\r\n      \"target\": \"q2\",\r\n      \"metadata\": {\r\n        \"answer\": \"Yes\",\r\n        \"score\": -10\r\n      }\r\n    },\r\n    {\r\n      \"source\": \"q1\",\r\n      \"target\": \"q3\",\r\n      \"metadata\": {\r\n        \"answer\": \"No\",\r\n        \"score\": 10\r\n      }\r\n    },\r\n    {\r\n      \"source\": \"q2\",\r\n      \"target\": \"q4\",\r\n      \"metadata\": {\r\n        \"answer\": \"Yes, Riven is my Bae!\",\r\n        \"score\": -1000\r\n      }\r\n    },\r\n    {\r\n      \"source\": \"q2\",\r\n      \"target\": \"q4\",\r\n      \"metadata\": {\r\n        \"answer\": \"No, I play CS GO instead xD\",\r\n        \"score\": 1000\r\n      }\r\n    },\r\n    {\r\n      \"source\": \"q3\",\r\n      \"target\": \"q4\",\r\n      \"metadata\": {\r\n        \"answer\": \"Yes, I am a true gym rat!\",\r\n        \"score\": 200\r\n      }\r\n    },\r\n    {\r\n      \"source\": \"q3\",\r\n      \"target\": \"q4\",\r\n      \"metadata\": {\r\n        \"answer\": \"No less than that\",\r\n        \"score\": 0\r\n      }\r\n    },\r\n    {\r\n      \"source\": \"q4\",\r\n      \"target\": \"fn\"\r\n    }\r\n  ]\r\n}";

  const minJSONGraph1Str2 = "{\"nodes\":[{\"id\":\"h\",\"metadata\":{\"isHead\":true,\"title\":\"\"}},{\"id\":\"q1\",\"metadata\":{\"title\":\"Do you play video games?\"}},{\"id\":\"q2\",\"metadata\":{\"title\":\"Do you play League of Legends or World of Warcraft Classic?\"}},{\"id\":\"q3\",\"metadata\":{\"title\":\"Do you exercise at least twice a week?\"}},{\"id\":\"q4\",\"metadata\":{\"title\":\"Do you get more than 7 hours of sleep every night?\"}},{\"id\":\"fn\",\"metadata\":{\"isFinalNode\":true,\"title\":\"\"}}],\"edges\":[{\"source\":\"h\",\"target\":\"q1\"},{\"source\":\"q1\",\"target\":\"q2\",\"metadata\":{\"answer\":\"Yes\",\"score\":-10}},{\"source\":\"q1\",\"target\":\"q3\",\"metadata\":{\"answer\":\"No\",\"score\":10}},{\"source\":\"q2\",\"target\":\"q4\",\"metadata\":{\"answer\":\"Yes, Riven is my Bae!\",\"score\":-1000}},{\"source\":\"q2\",\"target\":\"q4\",\"metadata\":{\"answer\":\"No, I play CS GO instead xD\",\"score\":1000}},{\"source\":\"q3\",\"target\":\"q4\",\"metadata\":{\"answer\":\"Yes, I am a true gym rat!\",\"score\":200}},{\"source\":\"q3\",\"target\":\"q4\",\"metadata\":{\"answer\":\"No less than that\",\"score\":0}},{\"source\":\"q4\",\"target\":\"fn\"}]}";

  const minJSONGraph1Str3 = "{\"nodes\":[{\"id\":\"h\",\"metadata\":{\"isHead\":true,\"title\":\"\"}},{\"id\":\"q1\",\"metadata\":{\"title\":\"Do you play video games?\"}},{\"id\":\"q2\",\"metadata\":{\"title\":\"Do you play League of Legends or World of Warcraft Classic?\"}},{\"id\":\"q3\",\"metadata\":{\"title\":\"Do you exercise at least twice a week?\"}},{\"id\":\"q4\",\"metadata\":{\"title\":\"Do you get more than 7 hours of sleep every night?\"}},{\"id\":\"fn\",\"metadata\":{\"isFinalNode\":true,\"title\":\"\"}}],\"edges\":[{\"source\":\"h\",\"target\":\"q1\",\"metadata\":{\"answer\":\"\",\"score\":0}},{\"source\":\"q1\",\"target\":\"q2\",\"metadata\":{\"answer\":\"Yes\",\"score\":-10}},{\"source\":\"q1\",\"target\":\"q3\",\"metadata\":{\"answer\":\"No\",\"score\":10}},{\"source\":\"q2\",\"target\":\"q4\",\"metadata\":{\"answer\":\"Yes, Riven is my Bae!\",\"score\":-1000}},{\"source\":\"q2\",\"target\":\"q4\",\"metadata\":{\"answer\":\"No, I play CS GO instead xD\",\"score\":1000}},{\"source\":\"q3\",\"target\":\"q4\",\"metadata\":{\"answer\":\"Yes, I am a true gym rat!\",\"score\":200}},{\"source\":\"q3\",\"target\":\"q4\",\"metadata\":{\"answer\":\"No less than that\",\"score\":0}},{\"source\":\"q4\",\"target\":\"fn\",\"metadata\":{\"answer\":\"\",\"score\":0}}]}";

  describe("test createGraphFromJSON", () =>{
    test("should create a Graph object when called  with viable params.", () => {
      let graphFromJSON: Graph = GraphFactory.createGraphFromJSON(minJSONGraph1Str);
      console.log(`node count in parsed obj is: ${graphFromJSON.getNodes().length}`);
      console.log(graphFromJSON);
      expect(graphFromJSON).toBeInstanceOf(Graph);
    });
  });
});
