import { AxiosController } from './AxiosController'

/**
 * Class used for checking if the login data is correct.
 */
export class LoginService {
  private readonly url: string = '/login';
  private readonly axiosController: AxiosController;

  constructor() {
    this.axiosController = new AxiosController();
  }

/**
 * Logs the user out by clearing the token in the localStorage.
 */
  public logout() {
    localStorage.token = "";
  }

  /**
   *Verifies if the inputted login data is correct.
   * @param name - The input name.
   * @param password - The input password.
   * @returns Boolean promise with a token, if the login successful, empty token otherwise.
   */
  public async verifyLoginData(name: string, password: string): Promise<boolean> {
    const result = await this.axiosController.post(this.url, { name: name, password: password });

    let correctLogin: boolean = false;
    if (result.token && result.token != "") {
      correctLogin = true;
      localStorage.token = result.token;

    }
    return correctLogin;
  }

  /**
   * Checks if the token generated by verifyLoginData is still valid by sending the token to the backend.
   * @returns Boolean Promise if the token is still valid.
   */
  public async checkIfTokenStillValid(): Promise<boolean> {
    console.log("checkIfTokenStillValid ");

    let tok = localStorage.token;
    const result = await this.axiosController.post(this.url, { tok: tok });

    return result.success;
  }

}
